### ISSUE TITLE
Fallo en la ficha medieval, Fundry 11

### ISSUE THREAD

**Issue by Romanblader** [parvusdomus/ysystem#42]
Hola, Usando el tema de la **ficha medieval**, no se están guardando los datos de Biografia. Pero en las otras dos si.
Al acceder da este error:
commons.js:2070 Error: You are accessing Actor#data which has been migrated to Actor#system
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at logCompatibilityWarning (commons.js:2059:19)
    at Actor._logDataFieldMigration (commons.js:8533:14)
    at Object.get (commons.js:8497:18)
    at Object.getProperty (commons.js:2539:41)
    at FichaYsystem._activateEditor (foundry.js:6835:30)
    at HTMLDivElement.<anonymous> (foundry.js:6570:67)
    at Function.each (jquery.min.js:2:3003)
    at S.fn.init.each (jquery.min.js:2:1481)
    at FichaYsystem.activateListeners (foundry.js:6570:45)
    at FichaYsystem.activateListeners (FichaPJ.js:143:15)

Y luego hay una serie de errores como este:
commons.js:2070 Error: The content option for the editor handlebars helper has been deprecated. Please pass the content in as the first option to the helper and ensure it has already been enriched by TextEditor.enrichHTML if necessary
Deprecated since Version 10
Backwards-compatible support will be removed in Version 12
    at Object.logCompatibilityWarning (commons.js:2059:19)
    at Object.editor (foundry.js:7875:21)
    at Object.c (handlebars.min.js:27:19853)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:19:145)
    at c (handlebars.min.js:27:15429)
    at d (handlebars.min.js:27:15744)
    at e (handlebars.min.js:28:22748)
    at Object.h (handlebars.min.js:27:18738)
    at Object.c [as invokePartial] (handlebars.min.js:27:15036)
    at Object.eval [as main] (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:67:28)

Pasa solo con la ficha medieval.

**Comment by parvusdomus** [comment]
Gracias por el aviso, arreglado en la 1.5.4
